lang: en-US
title: witbore
email: witbore@gmail.com
description: Witbore's site.
url: "https://witbore.github.io"
author:
  name: witbore
  twitter: witbore
  picture: /assets/images/witbore.jpg
twitter_username: witbore
github_username: witbore
logo: /assets/images/witbore.jpg
search: false
search_full_content: false 

markdown: kramdown
theme: jekyll-theme-basically-basic
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

paginate: 10
paginate_path: /page:num/

exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Rakefile
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
